//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendAndDelete
{
    using System;
    using System.Collections.Generic;
    
    public partial class allerror
    {
        public int idAllErrors { get; set; }
        public int idError { get; set; }
        public System.DateTime TimeRaised { get; set; }
        public Nullable<System.DateTime> TimeCleared { get; set; }
        public int Status { get; set; }
        public Nullable<int> ClearType { get; set; }
        public Nullable<int> ClearingUser { get; set; }
        public string ExceptionMessage { get; set; }
        public string ProcessName { get; set; }
        public string ExceptionDetail { get; set; }
    }
}
