//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendAndDelete
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrbackedup
    {
        public string FileName { get; set; }
        public long FileSerialNumber { get; set; }
        public int SwitchId { get; set; }
        public Nullable<System.DateTime> FileTimeStamp { get; set; }
        public string Permission { get; set; }
    }
}
