//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendAndDelete
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrdecoded
    {
        public long idCDRDecoded { get; set; }
        public string FileName { get; set; }
        public long FileSerialNumber { get; set; }
        public string FullPathLocal { get; set; }
        public Nullable<int> idSwitch { get; set; }
        public Nullable<System.DateTime> DecodeTimeServer1 { get; set; }
        public Nullable<System.DateTime> DecodeTimeServer2 { get; set; }
        public int NoOfRecordsSrv1 { get; set; }
        public int NoOfRecordsSrv2 { get; set; }
        public long StartSequenceNumberSrv1 { get; set; }
        public long StartSequenceNumberSrv2 { get; set; }
        public long EndSequenceNumberSrv1 { get; set; }
        public int EndSequenceNumberSrv2 { get; set; }
        public Nullable<sbyte> LoadingMarked { get; set; }
    }
}
