//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendAndDelete
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdrtemploaded
    {
        public int SwitchId { get; set; }
        public decimal idCall { get; set; }
        public decimal SequenceNumber { get; set; }
        public long FileSerialNo { get; set; }
        public Nullable<byte> CallDirection { get; set; }
        public string IncomingRoute { get; set; }
        public string OriginatingIP { get; set; }
        public Nullable<int> OPC { get; set; }
        public Nullable<int> OriginatingCIC { get; set; }
        public string OriginatingCalledNumber { get; set; }
        public string TerminatingCalledNumber { get; set; }
        public string OriginatingCallingNumber { get; set; }
        public string TerminatingCallingNumber { get; set; }
        public Nullable<byte> CustomerPrePaid { get; set; }
        public Nullable<float> DurationSec { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> ConnectTime { get; set; }
        public Nullable<System.DateTime> AnswerTime { get; set; }
        public Nullable<byte> ChargingStatus { get; set; }
        public Nullable<float> PDD { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> MinuteID { get; set; }
        public Nullable<byte> ReleaseDirection { get; set; }
        public Nullable<int> ReleaseCauseSystem { get; set; }
        public Nullable<int> ReleaseCauseEgress { get; set; }
        public string OutgoingRoute { get; set; }
        public string TerminatingIP { get; set; }
        public Nullable<int> DPC { get; set; }
        public Nullable<int> TerminatingCIC { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> CustomerCallNumber { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> SupplierCallNumber { get; set; }
        public string MatchedPrefixY { get; set; }
        public Nullable<float> USDRateY { get; set; }
        public string MatchedPrefixCustomer { get; set; }
        public string MatchedPrefixSupplier { get; set; }
        public Nullable<float> CustomerCost { get; set; }
        public Nullable<float> SupplierCost { get; set; }
        public Nullable<float> CostANSIn { get; set; }
        public Nullable<float> CostICXIn { get; set; }
        public Nullable<float> CostVATCommissionIn { get; set; }
        public Nullable<float> IGWRevenueIn { get; set; }
        public Nullable<float> RevenueANSOut { get; set; }
        public Nullable<float> RevenueIGWOut { get; set; }
        public Nullable<float> RevenueICXOut { get; set; }
        public Nullable<float> RevenueVATCommissionOut { get; set; }
        public Nullable<float> SubscriberChargeXOut { get; set; }
        public Nullable<float> CarrierCostYIGWOut { get; set; }
        public string ANSPrefixOrig { get; set; }
        public Nullable<int> AnsIdOrig { get; set; }
        public string AnsPrefixTerm { get; set; }
        public Nullable<int> AnsIdTerm { get; set; }
        public Nullable<byte> CustomerCurrency { get; set; }
        public Nullable<byte> SupplierCurrency { get; set; }
        public Nullable<byte> ReleaseCauseIngress { get; set; }
        public Nullable<decimal> CustomerCallNumberANS { get; set; }
        public Nullable<decimal> SupplierCallNumberANS { get; set; }
        public Nullable<byte> CalledPartyNOA { get; set; }
        public Nullable<byte> CallingPartyNOA { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<byte> MonthId { get; set; }
        public Nullable<int> DayId { get; set; }
        public Nullable<float> BTRCTermRate { get; set; }
        public Nullable<int> WeekDayId { get; set; }
        public Nullable<int> E1Id { get; set; }
        public string MediaIP1 { get; set; }
        public string MediaIP2 { get; set; }
        public string MediaIP3 { get; set; }
        public string MediaIP4 { get; set; }
        public Nullable<float> CallCancelDuration { get; set; }
        public Nullable<int> E1IdOut { get; set; }
        public Nullable<sbyte> HourId { get; set; }
        public Nullable<sbyte> HalfHourId { get; set; }
        public Nullable<sbyte> FifteenMinutesId { get; set; }
        public Nullable<sbyte> FiveMinutesId { get; set; }
        public Nullable<sbyte> MediationComplete { get; set; }
        public Nullable<long> TempTransactionId { get; set; }
        public Nullable<byte> ConnectedNumberType { get; set; }
        public string RedirectingNumber { get; set; }
        public Nullable<byte> CallForwardOrRoamingType { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<int> field1 { get; set; }
        public Nullable<int> field2 { get; set; }
        public Nullable<int> field3 { get; set; }
        public string field4 { get; set; }
        public string field5 { get; set; }
    }
}
