//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendAndDelete
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public string jobname { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> creationtime { get; set; }
        public Nullable<System.DateTime> finishtime { get; set; }
        public string parameters { get; set; }
    }
}
