//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSendAndDelete
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class telcobrightmediationEntities : DbContext
    {
        public telcobrightmediationEntities()
            : base("name=telcobrightmediationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<allerror> allerrors { get; set; }
        public virtual DbSet<cdrbackedup> cdrbackedups { get; set; }
        public virtual DbSet<cdrdecoded> cdrdecodeds { get; set; }
        public virtual DbSet<cdrlisted> cdrlisteds { get; set; }
        public virtual DbSet<cdrreceived> cdrreceiveds { get; set; }
        public virtual DbSet<cdrtemploaded> cdrtemploadeds { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<lastjobcreated> lastjobcreateds { get; set; }
    }
}
